ALTER TYPE "CreditStatus" RENAME VALUE 'DRAFT' TO 'BORRADOR';
ALTER TYPE "CreditStatus" RENAME VALUE 'PENDING_APPROVAL' TO 'PENDIENTE_APROBACION';
ALTER TYPE "CreditStatus" RENAME VALUE 'APPROVED' TO 'APROBADO';
ALTER TYPE "CreditStatus" RENAME VALUE 'REJECTED' TO 'RECHAZADO';
ALTER TYPE "CreditStatus" RENAME VALUE 'ACTIVE' TO 'ACTIVO';
ALTER TYPE "CreditStatus" RENAME VALUE 'PAID' TO 'PAGADO';
ALTER TYPE "CreditStatus" RENAME VALUE 'OVERDUE' TO 'VENCIDO';
ALTER TYPE "CreditStatus" RENAME VALUE 'DEFAULTED' TO 'CASTIGADO';
ALTER TYPE "CreditStatus" RENAME VALUE 'CANCELED' TO 'CANCELADO';

ALTER TYPE "PaymentStatus" RENAME VALUE 'PENDING' TO 'PENDIENTE';
ALTER TYPE "PaymentStatus" RENAME VALUE 'PARTIAL' TO 'PARCIAL';
ALTER TYPE "PaymentStatus" RENAME VALUE 'PAID' TO 'PAGADO';
ALTER TYPE "PaymentStatus" RENAME VALUE 'OVERDUE' TO 'VENCIDO';
ALTER TYPE "PaymentStatus" RENAME VALUE 'CANCELED' TO 'CANCELADO';
