ALTER TABLE clients ADD COLUMN IF NOT EXISTS "hasSpouse" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS "spouseFullName" TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS "spousePhone" TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS "hasGuarantor" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS "guarantorFullName" TEXT;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS "guarantorPhone" TEXT;
